### ISSUE TITLE
可以写个教程如何输出 文档的json文件不

### ISSUE THREAD

**Issue by JHeLiu** [dotnet/AspNetCore.Docs.zh-cn#242]
[在此处输入反馈]
可以写个教程如何输出 文档的json文件不，因为目的需要是一台服务器的一个站点专门处理所有项目的 webapi文档。 我只要把一个json文件丢给远程服务器就可以了，我本机不想去处理这些，它可能更像生成项目一样， 右键生成 把这个json文件发布到远程服务器

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Swashbuckle 和 ASP.NET Core 入门](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by srvbpigh** [comment]
Hello, @JHeLiu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
你好，@JHeLiu

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。  

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。  

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  

Microsoft DOCS International Team
