### ISSUE TITLE
docker build

### ISSUE THREAD

**Issue by gogojames** [dotnet/AspNetCore.Docs.zh-cn#243]
204.79.197.219:443: read: connection reset by peer

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [ASP.NET Core 的 Docker 映像](https://docs.microsoft.com/zh-cn/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @gogojames
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Gonzalo-Salines** [comment]
你好，@gogojames，

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by gogojames** [comment]
你好，@Gonzalo-Salines,
        问题已解决。谢谢！

**Comment by V-vafune** [comment]
你好，@gogojames  

非常感谢你提供反馈。很高兴我们的文档满足你的期望。  

欢迎提供宝贵的反馈，以便我们继续改进体验。  

深深的祝福，  
Microsoft DOCS International Team
