### ISSUE TITLE
安装.NET Core Hosting Bundle之后之前的站点无法启动

### ISSUE THREAD

**Issue by zxj17815** [dotnet/AspNetCore.Docs.zh-cn#244]
在一个IIS里安装了安装.NET Core Hosting Bundle之后，之前在IIS上的aps.net Service应用无法正常使用了，打不开

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f92a99a8-6ffa-e5f9-b7ef-f13fa1e0f17b
* Version Independent ID: 51273790-5178-875b-010e-15d7725da535
* Content: [将 ASP.NET Core 应用发布到 IIS](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/publish-to-iis.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/publish-to-iis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @zxj17815
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
你好，@zxj17815  

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。  

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。  

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  

Microsoft DOCS International Team
