### ISSUE TITLE
i fully follow the tutorial but meet a error

### ISSUE THREAD

**Issue by Bdl-1989** [dotnet/AspNetCore.Docs.zh-cn#246]
![image](https://user-images.githubusercontent.com/48614612/75741299-25693580-5d45-11ea-9257-f7254331063f.png)

![image](https://user-images.githubusercontent.com/48614612/75741376-59dcf180-5d45-11ea-8aef-e83ed6f039ac.png)

**Comment by Bdl-1989** [comment]
i have tried both the version 3.0.0 and 3.1.2 of Microsoft.EntityFrameworkCore.SqlServer

**Comment by Bdl-1989** [comment]
"using Microsoft.EntityFrameworkCore;" is grey...

**Comment by Bdl-1989** [comment]
i solve it!!! by installing Microsoft.EntityFrameworkCore.InMemory...
the tutorial is not friendly and it should be updated!!!


![image](https://user-images.githubusercontent.com/48614612/75742205-e092ce00-5d47-11ea-9f49-0a7f207fc735.png)

**Comment by srvbpigh** [comment]
Hello, @Bdl-1989
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
