### ISSUE TITLE
中文翻译有错误

### ISSUE THREAD

**Issue by KillingMeNow** [dotnet/AspNetCore.Docs.zh-cn#248]
AspNetCore.SignalR。机 
应改为 AspNetCore.SignalR.Client

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 04f4bdfd-dfac-d6ae-4bd9-57439d300a5d
* Version Independent ID: 1f37f1ba-3e43-e726-f231-52acc6d26516
* Content: [SignalR 和 ASP.NET Core 之间的差异 SignalR](https://docs.microsoft.com/zh-cn/aspnet/core/signalr/version-differences?view=aspnetcore-3.1#how-to-identify-the-opno-locsignalr-version)
* Content Source: [aspnetcore/signalr/version-differences.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/signalr/version-differences.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by srvbpigh** [comment]
Hello, @KillingMeNow
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@KillingMeNow

感谢你的发布内容。

当前不接受有关机器翻译内容的翻译问题的发布内容。

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。

非常感谢你的支持。

Microsoft DOCS 全球体验团队
