### ISSUE TITLE
离线查看文档时，xref链接好像不起作用

### ISSUE THREAD

**Issue by epicblue** [dotnet/AspNetCore.Docs.zh-cn#249]
尝试使用markdownpad 2.5 查看，谢谢！

**Comment by srvbpigh** [comment]
Hello, @epicblue
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@epicblue
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by epicblue** [comment]
什么软件可以用来离线查看文档，我用markdown pro查看文档时，点击页面链接(xref链接)会出现查看错误，谢谢！

**Comment by CeciAc** [comment]
你好，@epicblue

非常感谢您的贡献。此反馈与产品相关，请使用“文档”页底部的“提供产品反馈”按钮，记录你的建议。

如果你有任何与文档相关的反馈，请通过此渠道进行记录。

我们非常感谢你对我们的文章的贡献。

Microsoft DOCS 国际团队
