### ISSUE TITLE
How do I export *.json files instead of accessing them directly

### ISSUE THREAD

**Issue by JHeLiu** [dotnet/AspNetCore.Docs.zh-cn#250]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Swashbuckle 和 ASP.NET Core 入门](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

1.How do I export *.json files instead of accessing them directly
2.If I can't export the json file, how do I get cross-domain access to the API that I interviewed on 3.1 and that cross-domain access is not allowed
3.Because I rewrote the swagger- UI, it was too ugly, so it was pretty.I now want to know how I can access this json file from another site, and how best to generate a json file
4.How do I remove this document generation from the production environment

**Comment by srvbpigh** [comment]
Hello, @JHeLiu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/AspNetCore.Docs #17266](https://github.com/dotnet/AspNetCore.Docs/issues/17266) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @JHeLiu, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/17266. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
