### ISSUE TITLE
文档内容太大，无法下载，怎么办？

### ISSUE THREAD

**Issue by myokok** [dotnet/AspNetCore.Docs.zh-cn#251]
文档内容太大，无法下载，怎么办？

**Comment by srvbpigh** [comment]
Hello, @myokok
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@myokok
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by V-vafune** [comment]
你好，@myokok ， 

我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？ 

顺祝商祺！ 

Microsoft DOCS 国际团队

**Comment by V-vafune** [comment]
你好，@myokok ， 

再次感谢你的评论。 

很遗憾，我们仍然缺少信息，无法处理你的反馈。我们当前将关闭此 GitHub 问题，但我们欢迎你在以后提交更多反馈。 

顺祝商祺！ 

Microsoft DOCS 国际团队
