### ISSUE TITLE
AddDbContext<MovieContext> 应改为AddDbContext<RazorPagesMovieContext>

### ISSUE THREAD

**Issue by peanut996** [dotnet/AspNetCore.Docs.zh-cn#256]
// The type or namespace name 'MovieContext' could not be found (are you missing a using directive or an assembly reference?)
在Razor的教程中实际并未定义MovieContext，而是RazorPagesMovieContext。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [在 ASP.NET Core 中向 Razor Pages 应用添加模型](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's a good error message. You missed a step.

Recommend closing.

**Comment by peanut996** [comment]
But I added the follwing code to `startup.cs`
```C#
using RazorPagesMovie.Data;
using Microsoft.EntityFrameworkCore;
```
And this's my dir information:
![图片](https://user-images.githubusercontent.com/32303768/78751081-2294dc80-79a4-11ea-936b-9b1889ea5196.png)

Maybe you can tell me the step I missed.  Thanks :）.
