### ISSUE TITLE
这里中文翻译明显不对

### ISSUE THREAD

**Issue by Witchie** [dotnet/AspNetCore.Docs.zh-cn#261]
在 Microsoft 开发人员门户中创建应用
```
将Microsoft.AspNetCore.身份验证.Microsoft 帐户NuGet 包添加到项目中。 

```

应该是Microsoft.AspNetCore.Authentication.MicrosoftAccount不翻译

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [微软帐户外部登录设置与ASP.NET核心](https://docs.microsoft.com/zh-cn/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @Witchie
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Witchie

感谢你的发布内容。 

当前不接受有关机器翻译内容的翻译问题的发布内容。 

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。 

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。 

非常感谢你的支持。 

Microsoft DOCS 全球体验团队
