### ISSUE TITLE
How to submit my translation?

### ISSUE THREAD

**Issue by mrhuo** [dotnet/AspNetCore.Docs.zh-cn#265]
I see that many documents are machine translation, which is not suitable for developers to read. I want to participate in translation and submit my translation results. What process is needed?
----
我看到有很多文档都是机器翻译，并不适合开发者阅读，我想参与翻译，提交我的翻译结果，需要什么流程？

**Comment by srvbpigh** [comment]
Hello, @mrhuo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @mrhuo 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
