### ISSUE TITLE
Web API测试

### ISSUE THREAD

**Issue by spring-rool** [dotnet/AspNetCore.Docs.zh-cn#272]
[在此处输入反馈]
如何测试控制器的create update delete操作方法

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [使用 ASP.NET Core 和 MongoDB 创建 Web API](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by srvbpigh** [comment]
Hello, @spring-rool
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/AspNetCore.Docs #18476](https://github.com/dotnet/AspNetCore.Docs/issues/18476) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@spring-rool 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/AspNetCore.Docs/issues/18476。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
