### ISSUE TITLE
url link error

### ISSUE THREAD

**Issue by varichs** [dotnet/AspNetCore.Docs.zh-cn#273]
[在此处输入反馈]
"用户和组" 的URL跳转地址错误

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7bf6fefc-557e-114a-a37c-90939e06b083
* Version Independent ID: 92da23e0-6dc5-170e-b489-2ad8bbd46dff
* Content: [SignalR HubContext](https://docs.microsoft.com/zh-cn/aspnet/core/signalr/hubcontext?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/hubcontext.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/signalr/hubcontext.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by srvbpigh** [comment]
Hello, @varichs
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @JasonCard 
can you please check this issue?
it looks like it replicates in all locales

**Comment by JasonCard** [comment]
Following up on this issue.

**Comment by varichs** [comment]
Thank you very much. The URL is normal
