### ISSUE TITLE
The url link of JavaScript client can't redirect

### ISSUE THREAD

**Issue by zhutoutou** [dotnet/AspNetCore.Docs.zh-cn#275]
![image](https://user-images.githubusercontent.com/30338453/83730151-3fcfe980-a67b-11ea-9f16-1aed2c37e1c8.png)

nothing happend when click the url,and also other page with jsclient in signal has same problem

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c888abac-0b7a-6529-e3a9-dc43ca14ffce
* Version Independent ID: 08a0cb80-db1e-0ca5-abd7-9bfc3a28b01e
* Content: [ASP.NET Core SignalR 客户端](https://docs.microsoft.com/zh-cn/aspnet/core/signalr/client-features?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/client-features.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/signalr/client-features.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by srvbpigh** [comment]
Hello, @zhutoutou
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @JasonCard 
this error seems to replicate in localized versions
can you please check it?

**Comment by JasonCard** [comment]
Hi @zhutoutou 

Thank you for reporting this issue.
We're looking into this and will update when fixed.

Best regards,
Jason
cc @CeciAc

**Comment by JasonCard** [comment]
Hi @zhutoutou 

This issue is now fixed.
Thank you again for your feedback.

Best regards,
Jason
