### ISSUE TITLE
左侧菜单栏部分链接指向错误

### ISSUE THREAD

**Issue by huhubun** [dotnet/AspNetCore.Docs.zh-cn#277]
左侧菜单栏，“Web API 应用”下的 “返回操作类型”、“处理 JSON Path 请求”、“格式化响应数据” 指向了错误的页面（如图），这看起来很像 #273 和 #275 反馈的问题。

![Web API 应用](https://user-images.githubusercontent.com/5095184/83845017-a536df80-a73a-11ea-9361-7ebdd65d382a.png)

另外在“安全和标识”下的“反请求伪造”、“性能”下的“负载测试和压力测试” 等，都有这样的问题。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [使用 ASP.NET Core 创建 Web API](https://docs.microsoft.com/zh-cn/aspnet/core/web-api/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by srvbpigh** [comment]
Hello, @huhubun
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@huhubun

感谢你的反馈。 

我们的工程团队已评审并接受你的建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面： https://docs.microsoft.com/zh-cn/aspnet/core/web-api/?view=aspnetcore-3.1

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 

深深的祝福， 
Microsoft DOCS International Team
