### ISSUE TITLE
希望翻译的关键字保留

### ISSUE THREAD

**Issue by jonny-xhl** [dotnet/AspNetCore.Docs.zh-cn#279]
[翻译的内容需要修改下，很多的关键字都被翻译了，例如保留关键字之类的关键字翻译了文档看起来很错乱]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [razor 语法参考 ASP.NET Core](https://docs.microsoft.com/zh-cn/aspnet/core/mvc/views/razor?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @jonny-xhl
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@jonny-xhl

感谢你的发布内容。

当前不接受有关机器翻译内容的翻译问题的发布内容。

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。

非常感谢你的支持。

Microsoft DOCS 全球体验团队

**Comment by JasonCard** [comment]
Hi @jonny-xhl 

Thank you for your feedback.
I'll follow up with writing team to prevent those keywords from being over-localized.

Best regards,
Jason
