### ISSUE TITLE
点击上一教程没反应

### ISSUE THREAD

**Issue by IDAmosWang** [dotnet/AspNetCore.Docs.zh-cn#280]
[在此处输入反馈]

页面结尾处的 点击上一教程没反应
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [ASP.NET Core 中的 Razor 页面和 EF Core - CRUD - 第 2 个教程（共 8 个）](https://docs.microsoft.com/zh-cn/aspnet/core/data/ef-rp/crud?view=aspnetcore-3.1)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Clicking at the end of the page does not respond to the previous tutorial

Transfer to https://github.com/dotnet/AspNetCore.Docs/issues

**Comment by srvbpigh** [comment]
Hello, @IDAmosWang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
@CeciAc bug on our side, Transfer to https://github.com/dotnet/AspNetCore.Docs/issues

**Comment by CeciAc** [comment]
Issue moved to [dotnet/AspNetCore.Docs #18817](https://github.com/dotnet/AspNetCore.Docs/issues/18817) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@IDAmosWang 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/AspNetCore.Docs/issues/18817。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
@CeciAc  I'm sorry, can you reopen this issue. The previous button works correct in english. It's not working in `/zh-cn/`

**Comment by IDAmosWang** [comment]
Yes, I think it was the Chinese document

**Comment by Rick-Anderson** [comment]
@JasonCard  can you reopen this? cc @CeciAc

**Comment by JasonCard** [comment]
Hi @IDAmosWang 

Thank you for reporting this issue.
I'm following up on this issue and will update when resolved.

cc @Rick-Anderson @CeciAc

**Comment by JasonCard** [comment]
Hi @IDAmosWang

Thank you again for reporting this issue.
It is now fixed.
