### ISSUE TITLE
希望调整“使用英语阅读”开关的位置

### ISSUE THREAD

**Issue by cttoy** [dotnet/AspNetCore.Docs.zh-cn#302]
在阅读文章时，有时需要随时通过“使用英语阅读”来切换中文和英文。目前这个切换功能固定在页面顶部，希望把这个功能放在右侧的浮动导航上，和“此页面有帮助吗”和“本文内容”放在一起。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor 托管模型](https://docs.microsoft.com/zh-cn/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by cttoy** [comment]
I have post it to https://github.com/MicrosoftDocs/feedback/issues.

**Comment by guardrex** [comment]
是的，@ cttoy。你是对的。他们仅在此处处理本地化和翻译问题。文档反馈库是他们接受文档系统反馈的地方。

Shì de,@ cttoy. Nǐ shì duì de. Tāmen jǐn zài cǐ chù chǔlǐ běndì huà hé fānyì wèntí. Wéndàng fǎnkuì kù shì tāmen jiēshòu wén dǎng xìtǒng fǎnkuì dì dìfāng.

Yes, @cttoy. You are correct. They only work on localization and translation issues here. The docs feedback repo is where they accept documentation system feedback.
