### ISSUE TITLE
some inexplicably symbols On the Chinese page

### ISSUE THREAD

**Issue by skywshing** [dotnet/AspNetCore.Docs.zh-cn#331]
On the Chinese page, some inexplicably symbols appear, such as :::no-loc:::

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [ASP.NET Core 中的 :::no-loc(Razor)::: Pages 介绍](https://docs.microsoft.com/zh-cn/aspnet/core/razor-pages/?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Refresh your page with a hard refresh. ^F5
That's been fixed. Please close this issue after you confirm the fix.

**Comment by Rick-Anderson** [comment]
Nevermind, I see it
![image](https://user-images.githubusercontent.com/3605364/99018116-700a9680-24fd-11eb-9148-dcbb151ee027.png)

**Comment by Rick-Anderson** [comment]
@JasonCard  looks like bug has moved to the headings.

**Comment by skywshing** [comment]
Thank you for your reply !

**Comment by JasonCard** [comment]
@skywshing Thank you again for reporting this issue and it's now fixed.
