### ISSUE TITLE
The translated Chinese expression means the opposite 翻译成中文后表达的意思刚好相反

### ISSUE THREAD

**Issue by RiccoYuan** [dotnet/AspNetCore.Docs.zh-cn#350]
https://docs.microsoft.com/zh-cn/aspnet/core/performance/performance-best-practices?view=aspnetcore-5.0#optimize-data-access-and-io

> Do use no-tracking queries in Entity Framework Core when accessing data for read-only purposes. EF Core can return the results of no-tracking queries more efficiently.

Chinese document display

> 在访问数据时， 请不要 在 Entity Framework Core 中使用 无跟踪查询。 EF Core 可以更有效地返回无跟踪查询的结果。

The meaning is reversed, should be
> 当出于只读目的访问数据时，请在Entity Framework Core中使用无跟踪查询。 EF Core可以更有效地返回无跟踪查询的结果。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core 性能最佳做法](https://docs.microsoft.com/zh-cn/aspnet/core/performance/performance-best-practices?view=aspnetcore-5.0)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JasonCard  this is a serious translation error. Who do I notify?

**Comment by JasonCard** [comment]
@RiccoYuan @Rick-Anderson Thank you for flagging this issue. I'm the correct contact for translation issues in Dev Tools & Services content. I'll follow up to get that particular sentence human translated and fixed.

**Comment by JasonCard** [comment]
@RiccoYuan This translation is now fixed :)
当出于只读目的访问数据时，请 在Entity Framework Core中使用 无跟踪查询。 EF Core可以更有效地返回无跟踪查询的结果。
