### ISSUE TITLE
内容错误

### ISSUE THREAD

**Issue by slaners** [dotnet/AspNetCore.Docs.zh-cn#357]
创建ASP.NET Core API后，ctrl+F5是灰色的，无法点击

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [教程：使用 ASP.NET Core 创建 Web API](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Translates to After creating ASP.NET Core API, ctrl+F5 is gray and cannot be clicked

Recommend closing.
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
